config/routes.rb
Rails.application.routes.draw do
  root :to => "readings#index"
  resources :readings
  devise_for :users

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :set_reading, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.find_by_user_id(current_user.id)
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
  end

  # GET /readings/new
  def new
    @reading = Reading.new
  end

  # GET /readings/1/edit
  def edit
  end

  # POST /readings
  # POST /readings.json
  def create
    if params[:m_value].present?
      if  Reading.find_by_user_id(current_user.id)
        @reading = Reading.find_by_user_id(current_user.id)
        @reading.update(main_slider_values: params[:m_value])
        @reading.save!
      else
        Reading.create(main_slider_values: params[:m_value], user_id: current_user.id)
      end
    end
    if params[:m_value_1].present? 
      if Reading.find_by_user_id(current_user.id)
        @reading = Reading.find_by_user_id(current_user.id)
        @reading.update(s1: params[:m_value_1])
        @reading.save!
      else
        Reading.create(s1: params[:m_value_1], user_id: current_user.id)
      end
    end
    if params[:m_value_2].present? 
      if  Reading.find_by_user_id(current_user.id)
        @reading = Reading.find_by_user_id(current_user.id)
        @reading.update(s2: params[:m_value_2])
        @reading.save!
      else
        Reading.create(s2: params[:m_value_2], user_id: current_user.id)
      end
    end
    if params[:m_value_3].present? 
    if Reading.find_by_user_id(current_user.id)
      @reading = Reading.find_by_user_id(current_user.id)
      @reading.update(s3: params[:m_value_3])
      @reading.save!
    else
      Reading.create(s3: params[:m_value_3], user_id: current_user.id)
    end
    end
    if params[:m_value_4].present? 
      if Reading.find_by_user_id(current_user.id)
      @reading = Reading.find_by_user_id(current_user.id)
      @reading.update(s4: params[:m_value_4])
      @reading.save!
    else
      Reading.create(s4: params[:m_value_4], user_id: current_user.id)
    end
    end
    if params[:m_value_5].present? 
      if Reading.find_by_user_id(current_user.id)
      @reading = Reading.find_by_user_id(current_user.id)
      @reading.update(s5: params[:m_value_5])
      @reading.save!
    else
      Reading.create(s5: params[:m_value_5], user_id: current_user.id)
    end
    end
    if params[:m_value_6].present? 
      if Reading.find_by_user_id(current_user.id)
      @reading = Reading.find_by_user_id(current_user.id)
      @reading.update(s6: params[:m_value_6])
      @reading.save!
    else
      Reading.create(s6: params[:m_value_6], user_id: current_user.id)
    end
    end
    if params[:m_value_7].present? 
    if Reading.find_by_user_id(current_user.id)
      @reading = Reading.find_by_user_id(current_user.id)
      @reading.update(s7: params[:m_value_7])
      @reading.save!
    else
      Reading.create(s7: params[:m_value_7], user_id: current_user.id)
    end
    end
    if params[:m_value_8].present? 
    if Reading.find_by_user_id(current_user.id)
      @reading = Reading.find_by_user_id(current_user.id)
      @reading.update(s8: params[:m_value_8])
      @reading.save!
    else
      Reading.create(s8: params[:m_value_8], user_id: current_user.id)
    end
    end
    if params[:m_value_9].present? 
    if Reading.find_by_user_id(current_user.id)
      @reading = Reading.find_by_user_id(current_user.id)
      @reading.update(s9: params[:m_value_9])
      @reading.save!
    else
      Reading.create(s9: params[:m_value_9], user_id: current_user.id)
    end
    end
    if params[:m_value_0].present? 
      if Reading.find_by_user_id(current_user.id)
      @reading = Reading.find_by_user_id(current_user.id)
      @reading.update(s10: params[:m_value_0])
      @reading.save!
    else
      Reading.create(s10: params[:m_value_0], user_id: current_user.id)
    end
    end
    redirect_to readings_url
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to readings_url, notice: 'Reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reading_params
      params.require(:reading).permit(:user_id, :main_slider_values, :s1, :s2, :s3, :s4, :s5, :s6, :s7, :s8, :s9, :s10)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Slider1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Slider1" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/readings/_form.html.erb
<%= form_for(@reading) do |f| %>
  <% if @reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% @reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :main_slider_values %><br>
    <%= f.number_field :main_slider_values %>
  </div>
  <div class="field">
    <%= f.label :s1 %><br>
    <%= f.number_field :s1 %>
  </div>
  <div class="field">
    <%= f.label :s2 %><br>
    <%= f.number_field :s2 %>
  </div>
  <div class="field">
    <%= f.label :s3 %><br>
    <%= f.number_field :s3 %>
  </div>
  <div class="field">
    <%= f.label :s4 %><br>
    <%= f.number_field :s4 %>
  </div>
  <div class="field">
    <%= f.label :s5 %><br>
    <%= f.number_field :s5 %>
  </div>
  <div class="field">
    <%= f.label :s6 %><br>
    <%= f.number_field :s6 %>
  </div>
  <div class="field">
    <%= f.label :s7 %><br>
    <%= f.number_field :s7 %>
  </div>
  <div class="field">
    <%= f.label :s8 %><br>
    <%= f.number_field :s8 %>
  </div>
  <div class="field">
    <%= f.label :s9 %><br>
    <%= f.number_field :s9 %>
  </div>
  <div class="field">
    <%= f.label :s10 %><br>
    <%= f.number_field :s10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing Reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

app/views/readings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Readings</h1>
<% if @readings.present? %>
	<div id="slider" data-slider-value= "<%= @readings.present? ? @readings.main_slider_values : "0" %>" data-s1= "<%= @readings.s1? ? @readings.s1 : "0" %>" data-s2= "<%= @readings.s2? ? @readings.s2 : "0" %>" data-s3= "<%= @readings.s3? ? @readings.s3 : "0" %>" data-s4= "<%= @readings.s4? ? @readings.s4 : "0" %>" data-s5= "<%= @readings.s5? ? @readings.s5 : "0" %>" data-s6= "<%= @readings.s6? ? @readings.s6 : "0" %>" data-s7= "<%= @readings.s7? ? @readings.s7 : "0" %>" data-s8= "<%= @readings.s8? ? @readings.s8 : "0" %>" data-s9= "<%= @readings.s9? ? @readings.s9 : "0" %>" data-s10= "<%= @readings.s10? ? @readings.s10 : "0" %>"></div>
	<div id="create-pane"></div>
<% else %>
	<div id="slider"></div>
	<div id="create-pane"></div>
<% end %>

app/views/readings/new.html.erb
<h1>New Reading</h1>

<%= render 'form' %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reading.user %>
</p>

<p>
  <strong>Main slider values:</strong>
  <%= @reading.main_slider_values %>
</p>

<p>
  <strong>S1:</strong>
  <%= @reading.s1 %>
</p>

<p>
  <strong>S2:</strong>
  <%= @reading.s2 %>
</p>

<p>
  <strong>S3:</strong>
  <%= @reading.s3 %>
</p>

<p>
  <strong>S4:</strong>
  <%= @reading.s4 %>
</p>

<p>
  <strong>S5:</strong>
  <%= @reading.s5 %>
</p>

<p>
  <strong>S6:</strong>
  <%= @reading.s6 %>
</p>

<p>
  <strong>S7:</strong>
  <%= @reading.s7 %>
</p>

<p>
  <strong>S8:</strong>
  <%= @reading.s8 %>
</p>

<p>
  <strong>S9:</strong>
  <%= @reading.s9 %>
</p>

<p>
  <strong>S10:</strong>
  <%= @reading.s10 %>
</p>

<%= link_to 'Edit', edit_reading_path(@reading) %> |
<%= link_to 'Back', readings_path %>